### PR TITLE
Park in new garage / dry boat spawn

### PR DESCRIPTION
**Pull request by CryptoGenics**
Solves issue with parking a vehicle in a new garage and still having to pay transfer fee.

### CODE REVIEW

**Comment by TanguyOrtegat** [comment]
thanks for your improvments! bu where is server file ? and please could you bundle your changes ? thanks

**Comment by CryptoGenics** [comment]
There are no changes for the server files. Just added the trigger "esx_eden_garage:MoveGarage" already used when paying to changing garage location to the vehicle and trailer return.

**Comment by CryptoGenics** [comment]
Added Boat Spawn marker so you do not have to swim to spawn in your boat.

**Comment by TarisGN** [comment]
i've got this error when i put a car in anither garage than the one that i tranfered :
`[esx_jb_eden_garage2] An error happens on MySQL for query "UPDATE owned_vehicles SET garage_name =@garage_name WHERE plate='HES 728'": ER_BAD_NULL_ERROR: Column 'garage_name' cannot be null[0m`

**Comment by CryptoGenics** [comment]
With my fix? Did you change the garage to garage_name in the client 247 and 264 as well as add the move garage trigger?

**Comment by CryptoGenics** [comment]
Might be an issue with your garage_name in SQL

**Comment by TarisGN** [comment]
Yup, i took your whole client file.

**Comment by CryptoGenics** [comment]
Fixed

**Comment by TanguyOrtegat** [comment]
thanks for contributing to the script and make it better :)

**Pull request merged**
