### PR TITLE
Update config

### PR DESCRIPTION
**Pull request by boermansjo**
Garage lake was not correct

### CODE REVIEW

**Comment by boermansjo** [comment]
I will changed it. But does it matter ? The type can only be an integer.

**Comment by TanguyOrtegat** [comment]
> I will changed it. But does it matter ? The type can only be an integer.

yes, in fivem docs, it is written it must be double, even if intiger works, best is using double

**Comment by boermansjo** [comment]
It is changed into doubles. I agree that natives uses floats. But the drawmarker is special :  `void DRAW_MARKER(int type, float posX, float posY, float posZ, float dirX, float dirY, float dirZ, float rotX, float rotY, float rotZ, float scaleX, float scaleY, float scaleZ, int red, int green, int blue, int alpha, BOOL bobUpAndDown, BOOL faceCamera, int p19, BOOL rotate, char* textureDict, char* textureName, BOOL drawOnEnts);`

**Comment by TanguyOrtegat** [comment]
oh yea, i oversaw that sorry :) you were correct :) leave it as it is  i ll push

**Comment by boermansjo** [comment]
I changed it already into 1.0
Still learning a lot of new stuff so thanks for pointing stuff out ;)

**Comment by TanguyOrtegat** [comment]
yea but type should be like you had done lol an int , but yea so what :), yea helping, maing scripts better, you learn more then always asking on fivem

**Pull request merged**
